### ISSUE TITLE
sourceMappingURL Directive Missing

### ISSUE THREAD

**Issue by DavidTimms** [6to5/grunt-6to5#11]
Hi, I'm not sure if this issue needs to be raised here or in the main 6to5 repo.

I've set `sourceMap: true` in my gruntfile options, and the source maps are produced, but the sourceMappingURL directive is not added to the output JS files. `sourceMap: 'inline'` appears to add the directive correctly.

**Comment by hummlas** [comment]
I'm having the same issue

**Comment by gefinity** [comment]
Also having his issue, had a quick look, doesn't seem to be anything in the lib even trying to add this, did it work before? (just using this today)
Could only find Utils.addSourceMappingUrl referenced from CLI api
