### ISSUE TITLE
Support for minification+source maps.

### ISSUE THREAD

**Issue by stebru** [6to5/grunt-6to5#15]
Would be nice if one could minify the ES5 output files + being able to map the minified files back to the original ES6 source files. Unsure if this is a grunt-6to5 task, or if 6to5 should handle this?

**Comment by sindresorhus** [comment]
That's a job for grunt-contrib-uglify.

**Comment by stebru** [comment]
Ah, ok.

**Comment by stebru** [comment]
@sindresorhus Isn't it possible to do in grunt, like you have done in the gulp plugin? https://www.npmjs.com/package/gulp-6to5 

Or should I just switch to using gulp?

**Comment by sindresorhus** [comment]
>  Isn't it possible to do in grunt, like you have done in the gulp plugin?

You can't compare them directly.

> Or should I just switch to using gulp?

Yes ;)

**Comment by stebru** [comment]
I'll switch ;)
