### ISSUE TITLE
sourceMap: "inline" option generates both "inline" and external file

### ISSUE THREAD

**Issue by zaggino** [6to5/grunt-6to5#18]
I have following settings:
```
"6to5": {
            options: {
                sourceMap: "inline",
                modules: "amd",
                experimental: true
            },
            src: {
                files: [{
                    expand: true,
                    cwd   : "src/",
                    src   : [ "**/*.{jsx,es6}" ],
                    dest  : "dist/",
                    ext   : ".js"
                }]
            }
        }
```
And in my `dist/` directory I always get compiled file with inline sourceMap (correct) but also `.js.map` file. Why?

**Comment by sindresorhus** [comment]
@sebmck `6to5` returns a sourcemap in `results.map` even though `inline` is specified. Wouldn't it be better if it didn't?

**Comment by sebmck** [comment]
@sindresorhus Hm, not sure. So I assume the issue is that `grunt-6to5` assumes that if 6to5 returned a sourcemap then it has to save it?

**Comment by zaggino** [comment]
Well, I guess it doesn't make any sense to have both `inline` and `external` sourceMaps when I asked only for an `inline` one. So `grunt-6to5` shouldn't save the `.js.map` file in this case.

**Comment by sindresorhus** [comment]
@sebmck Yes. I can easily check the option for `inline`/false, but would be better IMHO if it wasn't returned then.

@zaggino Yes, that's not what we're discussing. Just hold on tight. We'll fix this asap one way or another.

**Comment by sebmck** [comment]
@sindresorhus Fair call. Will be available in the next patch.

**Comment by sindresorhus** [comment]
Thanks :)
